#----------------------------------------------------------------------
# This file was generated by C:\devel\tools\img2pyFE.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Textfield_Rename = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALpJ"
    "REFUOI3tk8EJwkAQRd/fRLEBK0gJOdlHujDifYsQwQ7SjGwJqSCLHoU9hOB6UVASE8GLBz/M"
    "YYaZ94eBkUzCNzJfTf8EQM65ONZQVRVZltE0DUVR9Bucc7HrutEoy3Kw7r2P6QO0PRyRBDEi"
    "AQIBu/WKEMLbDdPnZL5YgiLGXJmlIlzOkzd4ASgBuGIMGHPf5FOAgDacENAp0grE6H1fAfvN"
    "atpuQPLej9pYa8nznLqusdb2Af9f4AaXc2bmFfhk/wAAAABJRU5ErkJggg==")
getTextfield_RenameData = Textfield_Rename.GetData
getTextfield_RenameImage = Textfield_Rename.GetImage
getTextfield_RenameBitmap = Textfield_Rename.GetBitmap

#----------------------------------------------------------------------
Arrow_Down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQxJ"
    "REFUOI2lkzFLQ0EQhEcNSCCVIpGXRkggCIpiFUkXLAyCv0JQCzv9ISLYCP4OwcJGECvBToIW"
    "YiEYUibvdm73LF6nnvLOaXfvY2ZvF/inpmKF47uDEEKAeoN6xVnv8sfe6RjAzNCZ62JzoQsK"
    "ow4qsYJS4c3DzEDx5QGkLwDBILkkAFwBUDNInhBBHEFVWFC4FAfiBFTCgqZFkFyKCKkO3ISg"
    "EpriYPt8q1OtVEHzMFO4X4b4bZH6p70rHec39fk6qB40j2wxw8pRe9Leb17/CaiN3nfd2L9+"
    "DIfwVnwlSYjj28xodudrf/QWNk5WHxpZY11VMXh6fhxcvKxFc8S0fNi6be0t3Zd+WEafYK+k"
    "p4E/rQYAAAAASUVORK5CYII=")
getArrow_DownData = Arrow_Down.GetData
getArrow_DownImage = Arrow_Down.GetImage
getArrow_DownBitmap = Arrow_Down.GetBitmap

#----------------------------------------------------------------------
Arrow_Up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQlJ"
    "REFUOI21kL1KA1EQhU/8C4ogFlksJIjY2gqa59BG22xKER/AB4oQFUVbIYJbiaAoYpN6QwJG"
    "yL3zd61sgruBXTzlzJmPjwH+M6cPcXJ83+zmdWayFifd+Lk2v7YTVaNG6/boKatXmRycvewv"
    "jIarr7VqtLWxvAkzw3v/Db209zEOle32QZtyDb6GKzfCsi6iEBNIECzOLsF7rtvo+2qqwW+a"
    "14dhr96AmiH5TNAfpLud+O5xsjeXBSDPYFVYUKSDFBd/HE8BEFgZFhTkKKuWA3AEMYEGhS8C"
    "8GMGK0PLGLAJzBTecQEDR2CV8j+woGBfwIAcQZRhMDBJAYBndM4vISxQ0UxA6fwAMoqrUD2w"
    "uKAAAAAASUVORK5CYII=")
getArrow_UpData = Arrow_Up.GetData
getArrow_UpImage = Arrow_Up.GetImage
getArrow_UpBitmap = Arrow_Up.GetBitmap

#----------------------------------------------------------------------
Textfield_Add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQxJ"
    "REFUOI1jYBgFjCdPnvxPiQEsDAwMDMbGxmRpfvPmDQMTjHP27FmyDGEirITGBrAQq3D32Y0M"
    "+y5sZvj49T3D7z+/GVyM/BicdQIQBuALyG0nVzGcf7abwd7alEFGSJVh/9UNDJsuT2V49Pwe"
    "A4u8vDzDmzdv8Nq+/uhihgBPd4a/TH8Z9CVdGfZcW81goWvFsG7zSuKc71Nt+H/blTn/kcGm"
    "S1P/m2dL/icqEN98fPnj6rNjDB27ExkYGBgYOnYlMtx9dYnhP8P/H8zEGCBlwsP5+ddrOwVx"
    "BYY3354wfPz6iuHoxcMMnz78nMhInCcYGMyyJDoYGBmzGBkYeP8zMHxm+P9/2qlpLyoAzMZs"
    "4ud3QFIAAAAASUVORK5CYII=")
getTextfield_AddData = Textfield_Add.GetData
getTextfield_AddImage = Textfield_Add.GetImage
getTextfield_AddBitmap = Textfield_Add.GetBitmap

#----------------------------------------------------------------------
Textfield_Delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQhJ"
    "REFUOI1jYBgFjCdPnvxPiQEsDAwMDMbGxmRpfvPmDQMTjHP27FmyDGEirITGBrAQq/DZ5hkM"
    "TzdPY/j68DYDq7gUg7RPBgOPUyLCAHwB+WzzDIYPx1cyGAQnM7ArajN8v7SL4frRFQw/fjMw"
    "ML548YJgNF4vsmIwj85m4Lx7gIHh6REGBn4Bhjcs8gxXzj8kzvm7nVj+/Tu77j8yeF8v8X+3"
    "E8s/osLgH9P/p98ubJXh3pTF8PP7C4ZvDAwMnz8xM/xlZnjGTIwB6aYS/O9ePrNhYmNm+s38"
    "leHj2/8M954x/f37538XI3GeYGA4HC5b8e3ts3Smf4zy/5j+P/3H8H+6555/bQChU21fH0/9"
    "swAAAABJRU5ErkJggg==")
getTextfield_DeleteData = Textfield_Delete.GetData
getTextfield_DeleteImage = Textfield_Delete.GetImage
getTextfield_DeleteBitmap = Textfield_Delete.GetBitmap

#----------------------------------------------------------------------
Delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAl9J"
    "REFUOI2lkltL1GEQh5//nszdskKLde3sQiVZdiBKiNiLIlK62YtQzK5j2S/RV+gLlEkRYRAd"
    "ScWwIBCiICqK1m13azNrPay5/g/vvG8XkpVaN87lwPMwM7+BFZa1uJFLpxuNSKcY6TauF9Vo"
    "tJExbeke8dS15p4bmX8KCqlU0jPm0trd8fpISwvWuhqwbbyvRSYGBpicKH1RWqUP9t7uWyIo"
    "pFJJJfpK7YlEJLJvLzL6Br4WwHWxVq/H2rKF0t375LMfZo1xzx++/qhvQZC7cGGHNjypO94a"
    "Cx/ajwzdoTJnY4lHVSiIpQ3GtaHpAN8e9vNpLF9USh87dmtw1AdgoCvSUBerbm5Chh8gzhza"
    "qRCslNFTJaQ8gbYreE/62ZBIUO04MeP3ugACABo5F9mzC/32JZXJ76hX83eqLDpwKLoWlc1Q"
    "39LK1Kvhc8DFAIAy0hAIh+H9e3Acai/fXDay8c4zBGc8Vh08grzwGgDmV/AUulxGz0wTEvu/"
    "uSulwYC2FL9X0OrzXO5jvDpSg+RLjHeeWZ72+Qht3sp0Novx5PPCBKLV1dLICCYWR6YdgmuC"
    "S1gxBjF+gtvi5F8PoVFXFwTa5/X+CK8qlh4PETzVhnZ8WH7/PIiFiAEdoOZUO7nBe8w4laKy"
    "vF7445Ged7QnxciVjWtqIxsSJ3A/ZnAzGbSrqdoZJ7RpO4XBO2RL72aNkfNtD971/SUAeNZx"
    "MmmUuhQSt37TrqOEojEAKsU8mdfDzIr9xRiV/gUvEQA8PZtoFNvuVH7dbbSOGtdDBfQYonqM"
    "uNdOP/yQWcysqH4Ct+5AeSaDkFQAAAAASUVORK5CYII=")
getDeleteData = Delete.GetData
getDeleteImage = Delete.GetImage
getDeleteBitmap = Delete.GetBitmap

#----------------------------------------------------------------------
Add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAo9J"
    "REFUOI2lk0tIlGEUhp/5x1tl0sVSx+ziZBaVId2zkiCCECKwjVJBEERB0ICbaFdE0C6kRbXK"
    "pEWQmyQ0U7qHUJQVlaENWuMMkznOjDP6/993vr9V043adJYH3nMezvse+M/y/N44393kN1o3"
    "Ki0HxehiZQSldUQbaVHavd7c0DL41wHnuwL1IjSXzfeXVBavYVp2Po5xiE6M8HSgh+hoNKwd"
    "dfzKobab3zXen8Vam6vrK2rnVJfVEJkKMzjRT3jyM94sL1ULNpLUYzMjX7/Ura5b2v+q/cO7"
    "DMG5rhPlruZhtX+Lr6KoivvhO6RTaZSrycvLxcXFNjYrClbxpP8u74ODI2LUtrZj3R8tAMTd"
    "P3vWPN/iwuU8inQzqaZIq0kCa09xdGUT43aMsXiEp+F7bFq2AytHfI6S/QAWgNbmwKL5lbyP"
    "v2E0MUoinWA8FcvcJhQcRtkpUsmvfE4EqamsQYk+AJAFoIwqzcuezlAyiGNsTm44+4szF+tb"
    "AQh0NhIa/8iquetQWpX+IBBNSiVJOgmUV/3Td1cMHlyUaDIEjuhQKDa0ND83n/HJMQIPDpOK"
    "Jri870ZmM4DlsfAVLGQ4GkSLDmUIlJFrL4O9LJy+BFfZeEQzZ/aMXzYbcbGMh7KCJdzu60aJ"
    "XPtBoKTViHWkd+Ceb3P5Th4PdaCNJtDZiCsALjmWl9ry3XS8bCeenBixjd2aCdKzttexNXsq"
    "hsZi8bq4Hc3Z7t9FlpWN7aTJsbLxFy6nqng9HX236H37KiVaH+k7/eHJH1FuuLS73tGqWbKk"
    "pHbFVooKSsCFT7FhOl/0kEimwyLq+Isz/Zko//FMey/s8NuiGx2Rg2JU5plETAtq6vrzswOD"
    "v2v+q74Bs3Vib859UBQAAAAASUVORK5CYII=")
getAddData = Add.GetData
getAddImage = Add.GetImage
getAddBitmap = Add.GetBitmap

#----------------------------------------------------------------------
Pencil = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAY9J"
    "REFUOI2t0rFLW1EUx/Hvve+ZpyF5BNQQU2nFwRS1ZgitVaSIS6CULkJxy5+gLq1LwVUnBcW9"
    "i3SoUEGkrdChNC4aqdUh2mqUJGoIJq2giZpct7cE9YGe+X4O557fgTuWsPtwP/q8ppj07h0f"
    "iVpVUtLpSiRMo6pbt9vgbN93qkp+Ol5HEFKyPv+uKZc+nrY1QfJrUHn8I+juhwhpAFAu/OPX"
    "wmRZ2sF1oSl0U5BaneUiG+ciGwdAk/r5jRNY2MhTTC1QPjX4G8vgNv1k03/oHPwsNFv48BPq"
    "MoHR+BSRy1BI/CY49E3ANSlU4PMkDt9LstE1TrZ3CAz/tFzFDr5PBGzjigZfxlpU6M2MbWx9"
    "YSbyqKm51dh93DfOwc4iT0JFWxhAB7g01W7XwAeqHTVszK8Sy5doaOvhJLpE4SBD1/uVa9Oy"
    "LtGQGv9/TBB64GIrtkls+SNOr5dX4xs3Rq0BeFzaaJszR317mHLjMzL5I5Qo3YqtHQz01iqH"
    "lLwIePC5DarqzLnw22j/bfhe6gpUqroRWOTJnAAAAABJRU5ErkJggg==")
getPencilData = Pencil.GetData
getPencilImage = Pencil.GetImage
getPencilBitmap = Pencil.GetBitmap

