#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Sep 25 09:51:12 2008

import wx
import  wx.lib.mixins.listctrl  as  listmix
import sys

# begin wxGlade: extracode
# end wxGlade

class PluginListCtrl(wx.ListCtrl,
                   listmix.ListCtrlAutoWidthMixin,
                   listmix.CheckListCtrlMixin):

    def __init__(self, parent, ID, pos=wx.DefaultPosition,
                 size=wx.DefaultSize, style=0):
        wx.ListCtrl.__init__(self, parent, ID, pos, size, style)
        
        self.InsertColumn(0, "Plugin")
        self.InsertColumn(1, "Description")
        self.InsertColumn(2, "Author")
        self.InsertColumn(3, "Version")
        
        listmix.ListCtrlAutoWidthMixin.__init__(self)
        listmix.CheckListCtrlMixin.__init__(self)

    def Populate(self):
        # for normal, simple columns, you can add them like this:
        

        index = self.InsertStringItem(0, 'Plugin name')
        self.SetStringItem(index, 1, 'Description of plugin')
        self.SetStringItem(index, 2, 'Plugin Author')
        self.SetStringItem(index, 3, '1.0')
        self.CheckItem(index, True)

        #~ self.SetColumnWidth(0, wx.LIST_AUTOSIZE)
        #~ self.SetColumnWidth(1, wx.LIST_AUTOSIZE)
        #~ self.SetColumnWidth(2, wx.LIST_AUTOSIZE)
        #~ self.SetColumnWidth(3, wx.LIST_AUTOSIZE)

        #~ self.currentItem = 0

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.list_ctrl_1 = PluginListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        
        index = self.list_ctrl_1.InsertStringItem(0, 'Plugin name')
        self.list_ctrl_1.SetStringItem(index, 1, 'Description of plugin')
        self.list_ctrl_1.SetStringItem(index, 2, 'Plugin Author')
        self.list_ctrl_1.SetStringItem(index, 3, '1.0')
        self.list_ctrl_1.CheckItem(index, True)
        
        self.button_1 = wx.Button(self, -1, "Install Plugin")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Plugin Configuration")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("C:\\devel\\graphic resources\\famfamfam_silk_icons_v013\\icons\\plugin.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_1, 0, wx.ALL|wx.ALIGN_RIGHT, 6)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = MyDialog(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
